path:
  logs: ./log/elasticsearch
  data: ./es_index
cluster:
  name: bob
node:
  name: hulk
  master: true
network:
  host: 127.0.0.1
  publish_host: 127.0.0.1

discovery.zen.ping.multicast.enabled: false

